# Experiment 8: Bayesian Network for Medical Diagnosis

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('heart.csv')
df.head()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [3]:
df.shape

(303, 14)

In [4]:
df.isnull().sum()

age         0
sex         0
cp          0
trtbps      0
chol        0
fbs         0
restecg     0
thalachh    0
exng        0
oldpeak     0
slp         0
caa         0
thall       0
output      0
dtype: int64

In [7]:
df.drop(['oldpeak', 'slp', 'caa', 'thall'], axis=1, inplace=True)

df.head()

   age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  output
0   63    1   3     145   233    1        0       150     0       1
1   37    1   2     130   250    0        1       187     0       1
2   41    0   1     130   204    0        0       172     0       1
3   56    1   1     120   236    0        1       178     0       1
4   57    0   0     120   354    0        1       163     1       1

In [6]:
df.columns

Index(['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
       'exng', 'oldpeak', 'slp', 'caa', 'thall', 'output'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trtbps    303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalachh  303 non-null    int64
 8   exng      303 non-null    int64
 9   output    303 non-null    int64
dtypes: int64(10)
memory usage: 23.8 KB

In [9]:
df.describe()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,output
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,1.000000

In [10]:
!pip install pgmpy

Collecting pgmpy
  Downloading pgmpy-1.1.2-py3-none-any.whl.metadata (13 kB)
Collecting huggingface_hub>=0.23 (from pgmpy)
  Downloading huggingface_hub-1.30.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: networkx>=3.0 in c:\users\vennila\anaconda3\lib\site-packages (from pgmpy) (3.5)
Requirement already satisfied: numpy>=2.0 in c:\users\vennila\anaconda3\lib\site-packages (from pgmpy) (2.3.5)
Requirement already satisfied: scipy>=1.10 in c:\users\vennila\anaconda3\lib\site-packages (from pgmpy) (1.16.3)
Requirement already satisfied: scikit-learn>=1.2 in c:\users\vennila\anaconda3\lib\site-packages (from pgmpy) (1.7.2)
Requirement already satisfied: pandas>=1.5 in c:\users\vennila\anaconda3\lib\site-packages (from pgmpy) (2.3.3)
Requirement already satisfied: statsmodels>=0.14.5 in c:\users\vennila\anaconda3\lib\site-packages (from pgmpy) (0.14.5)
Requirement already satisfied: tqdm>=4.64 in c:\users\vennila\anaconda3\lib\site-packages (from pgmpy) (4.67.1)
Requirement already satisfied: pyparsing>=3.0 in c:\users\vennila\anaconda3\lib\site-packages (from pgmpy) (3.2.5)
Requirement already satisfied: joblib>=1.2 in c:\users\vennila\anaconda3\lib\site-packages (from pgmpy) (1.5.2)
Requirement already satisfied: opt_einsum>=3.3 in c:\users\vennila\anaconda3\lib\site-packages (from pgmpy) (3.4.0)
Collecting scikit-base>=0.12.4 (from pgmpy)
  Downloading scikit_base-1.1.1-py3-none-any.whl.metadata (8.8 kB)
Collecting click<9.0.0,>=8.4.2 (from huggingface_hub>=0.23->pgmpy)
  Downloading click-8.5.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: filelock>=3.10.0 in c:\users\vennila\anaconda3\lib\site-packages (from huggingface_hub>=0.23->pgmpy) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\vennila\anaconda3\lib\site-packages (from huggingface_hub>=0.23->pgmpy) (2025.10.0)
Collecting hf-xet<2.0.0,>=1.5.2 (from huggingface_hub>=0.23->pgmpy)
  Downloading hf_xet-1.6.0-cp38-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\vennila\anaconda3\lib\site-packages (from huggingface_hub>=0.23->pgmpy) (0.28.1)
Requirement already satisfied: packaging>=20.9 in c:\users\vennila\anaconda3\lib\site-packages (from huggingface_hub>=0.23->pgmpy) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\vennila\anaconda3\lib\site-packages (from huggingface_hub>=0.23->pgmpy) (6.0.3)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\vennila\anaconda3\lib\site-packages (from huggingface_hub>=0.23->pgmpy) (4.15.0)
Requirement already satisfied: anyio in c:\users\vennila\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (4.10.0)
Requirement already satisfied: certifi in c:\users\vennila\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (2026.7.22)
Requirement already satisfied: httpcore==1.* in c:\users\vennila\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (1.0.9)
Requirement already satisfied: idna in c:\users\vennila\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\vennila\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (0.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vennila\anaconda3\lib\site-packages (from pandas>=1.5->pgmpy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vennila\anaconda3\lib\site-packages (from pandas>=1.5->pgmpy) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vennila\anaconda3\lib\site-packages (from pandas>=1.5->pgmpy) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\vennila\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.5->pgmpy) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\vennila\anaconda3\lib\site-packages (from scikit-learn>=1.2->pgmpy) (3.5.0)
Requirement already satisfied: patsy>=0.5.6 in c:\users\vennila\anaconda3\lib\site-packages (from statsmodels>=0.14.5->pgmpy) (1.0.1)
Requirement already satisfied: colorama in c:\users\vennila\anaconda3\lib\site-packages (from tqdm>=4.64->pgmpy) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\vennila\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (1.3.0)
Downloading pgmpy-1.1.2-py3-none-any.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ----------------- ---------------------- 1.0/2.4 MB 2.4 MB/s eta 0:00:01
   --------------------- ------------------ 1.3/2.4 MB 2.5 MB/s eta 0:00:01
   ------------------------------ --------- 1.8/2.4 MB 2.2 MB/s eta 0:00:01
   -------------------------------------- - 2.4/2.4 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 2.4/2.4 MB 2.2 MB/s  0:00:01
Downloading huggingface_hub-1.30.0-py3-none-any.whl (796 kB)
   ---------------------------------------- 0.0/796.8 kB ? eta -:--:--
   ------------- -------------------------- 262.1/796.8 kB ? eta -:--:--
   ---------------------------------------- 796.8/796.8 kB 2.1 MB/s  0:00:00
Downloading click-8.5.0-py3-none-any.whl (125 kB)
Downloading hf_xet-1.6.0-cp38-abi3-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ------- -------------------------------- 0.8/4.0 MB 1.8 MB/s eta 0:00:02
   ------- -------------------------------- 0.8/4.0 MB 1.8 MB/s eta 0:00:02
   ---------- ----------------------------- 1.0/4.0 MB 1.1 MB/s eta 0:00:03
   ------------ --------------------------- 1.3/4.0 MB 1.2 MB/s eta 0:00:03
   ------------------ --------------------- 1.8/4.0 MB 1.5 MB/s eta 0:00:02
   ----------------------- ---------------- 2.4/4.0 MB 1.7 MB/s eta 0:00:02
   ---------------------------- ----------- 2.9/4.0 MB 1.7 MB/s eta 0:00:01
   ---------------------------- ----------- 2.9/4.0 MB 1.7 MB/s eta 0:00:01
   --------------------------------- ------ 3.4/4.0 MB 1.6 MB/s eta 0:00:01
   -------------------------------------- - 3.9/4.0 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 1.6 MB/s  0:00:02
Downloading scikit_base-1.1.1-py3-none-any.whl (162 kB)
Installing collected packages: scikit-base, hf-xet, click, huggingface_hub, pgmpy

   ---------------------------------------- 0/5 [scikit-base]
   ---------------------------------------- 0/5 [scikit-base]
   ---------------------------------------- 0/5 [scikit-base]
   -------- ------------------------------- 1/5 [hf-xet]
  Attempting uninstall: click
   -------- ------------------------------- 1/5 [hf-xet]
    Found existing installation: click 8.2.1
   -------- ------------------------------- 1/5 [hf-xet]
    Uninstalling click-8.2.1:
   -------- ------------------------------- 1/5 [hf-xet]
   ---------------- ----------------------- 2/5 [click]
      Successfully uninstalled click-8.2.1
   ---------------- ----------------------- 2/5 [click]
   ---------------- ----------------------- 2/5 [click]
   ---------------- ----------------------- 2/5 [click]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   ---------------------------------------- 5/5 [pgmpy]

Successfully installed click-8.5.0 hf-xet-1.6.0 huggingface_hub-1.30.0 pgmpy-1.1.2 scikit-base-1.1.1

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.51.0 requires protobuf<7,>=3.20, but you have protobuf 7.36.1 which is incompatible.

In [11]:
from pgmpy.models import BayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator, BayesianEstimator

C:\Users\Vennila\anaconda3\Lib\site-packages\pgmpy\estimators\__init__.py:4: FutureWarning: `pgmpy.estimators.StructureScore` is deprecated and will be removed in v1.3.0. Use `pgmpy.structure_score` instead.
  from .StructureScore import (

In [12]:
df.columns

Index(['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
       'exng', 'output'],
      dtype='object')

In [26]:
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.parameter_estimator import DiscreteMLE

model = DiscreteBayesianNetwork([
    ('age', 'output'),
    ('sex', 'output'),
    ('exng', 'output'),
    ('cp', 'output'),
    ('output', 'restecg'),
    ('output', 'chol')
])

model.fit(df, estimator=DiscreteMLE())

In [27]:
print(model.get_cpds('age'))

+---------+------------+
| age(29) | 0.00330033 |
+---------+------------+
| age(34) | 0.00660066 |
+---------+------------+
| age(35) | 0.0132013  |
+---------+------------+
| age(37) | 0.00660066 |
+---------+------------+
| age(38) | 0.00990099 |
+---------+------------+
| age(39) | 0.0132013  |
+---------+------------+
| age(40) | 0.00990099 |
+---------+------------+
| age(41) | 0.0330033  |
+---------+------------+
| age(42) | 0.0264026  |
+---------+------------+
| age(43) | 0.0264026  |
+---------+------------+
| age(44) | 0.0363036  |
+---------+------------+
| age(45) | 0.0264026  |
+---------+------------+
| age(46) | 0.0231023  |
+---------+------------+
| age(47) | 0.0165017  |
+---------+------------+
| age(48) | 0.0231023  |
+---------+------------+
| age(49) | 0.0165017  |
+---------+------------+
| age(50) | 0.0231023  |
+---------+------------+
| age(51) | 0.039604   |
+---------+------------+
| age(52) | 0.0429043  |
+---------+------------+
| age(53) | 0.0264026  |
+---------+------------+
| age(54) | 0.0528053  |
+---------+------------+
| age(55) | 0.0264026  |
+---------+------------+
| age(56) | 0.0363036  |
+---------+------------+
| age(57) | 0.0561056  |
+---------+------------+
| age(58) | 0.0627063  |
+---------+------------+
| age(59) | 0.0462046  |
+---------+------------+
| age(60) | 0.0363036  |
+---------+------------+
| age(61) | 0.0264026  |
+---------+------------+
| age(62) | 0.0363036  |
+---------+------------+
| age(63) | 0.029703   |
+---------+------------+
| age(64) | 0.0330033  |
+---------+------------+
| age(65) | 0.0264026  |
+---------+------------+
| age(66) | 0.0231023  |
+---------+------------+
| age(67) | 0.029703   |
+---------+------------+
| age(68) | 0.0132013  |
+---------+------------+
| age(69) | 0.00990099 |
+---------+------------+
| age(70) | 0.0132013  |
+---------+------------+
| age(71) | 0.00990099 |
+---------+------------+
| age(74) | 0.00330033 |
+---------+------------+
| age(76) | 0.00330033 |
+---------+------------+
| age(77) | 0.00330033 |
+---------+------------+

In [29]:
print(model.get_cpds('sex'))

+--------+----------+
| sex(0) | 0.316832 |
+--------+----------+
| sex(1) | 0.683168 |
+--------+----------+

In [30]:
print(model.get_cpds('exng'))

+---------+----------+
| exng(0) | 0.673267 |
+---------+----------+
| exng(1) | 0.326733 |
+---------+----------+